Feature/social media
nhsuk/permission-to-contact-prototype pull request #69
Opened 2020-12-01 19:24 UTC by mikaelmetthey

## Description

## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] CHANGELOG entry

2020-12-01 19:33 UTC, mcheung-nhs requested changes

2020-12-01 19:33 UTC, mcheung-nhs commented on app/views/social/index.html
> +        <li><a href="https://permission-to-contact-proto.herokuapp.com/social/normal">Option 1: Normal</a></li>
Maybe remove the full URL and have the link relative to the root, eg <a href="/social/normal">

2020-12-02 10:08 UTC, mikaelmetthey reviewed
Changed links to:
a href="/social/normal"

2020-12-02 17:26 UTC, mcheung-nhs approved these changes

2020-12-02 17:26 UTC, merged